/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TesteConexaoJDBC;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
public class App {



    public static void main(String[] args) {
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        
        String url = "jdbc:mysql://localhost:3306/todoApp";
        String user = "root";
        String password = "";
        
        try {
            // Carregar o driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
            
            // Estabelecer a conexão com o banco de dados
            connection = DriverManager.getConnection(url, user, password);
            
            // Criar uma declaração
            statement = connection.createStatement();
            
            // Executar uma consulta
            String query = "SELECT name FROM projects";
            resultSet = statement.executeQuery(query);
            
            // Exibir os resultados
            while (resultSet.next()) {
                String nome = resultSet.getString("name");
                System.out.println("Nome: " + nome);
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                // Fechar recursos
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

}
